/**
 * Generates the keyboard and accessibility section of every guide from one map.
 *
 * An agent cannot infer keyboard behaviour from a prop table, so it ships a div that
 * looks like a dialog and answers to nothing. The map is written by hand once — it is
 * a contract, not something a parser can find — and generated into the guides so it
 * cannot drift file by file. A guide with no entry in the map fails the check:
 * silence reads as "no keyboard behaviour", which is never what anyone meant.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { ROOT } from "./components.mjs";

const START = "<!-- a11y:start -->";
const END = "<!-- a11y:end -->";
const map = JSON.parse(readFileSync(join(ROOT, "guidelines/a11y-map.json"), "utf8")).components;

function guides(dir = join(ROOT, "guidelines"), out = []) {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
        const path = join(dir, entry.name);
        if (entry.isDirectory()) guides(path, out);
        else if (entry.name.endsWith(".md")) out.push(path);
    }
    return out;
}

const section = (contract) =>
    [
        START,
        "<!-- generated by scripts/a11y.mjs from guidelines/a11y-map.json — do not edit -->",
        "",
        "### Keyboard and accessibility",
        "",
        `**Role:** ${contract.role} · **Accessible name:** ${contract.name}`,
        "",
        contract.keys.length
            ? ["| Key | What happens |", "| :-- | :-- |", ...contract.keys.map(([k, v]) => `| \`${k}\` | ${v} |`)].join("\n")
            : "No keys: nothing here is interactive.",
        "",
        `**Focus.** ${contract.focus}`,
        "",
        contract.notes,
        END,
    ].join("\n");

const check = process.argv.includes("--check");
let stale = 0;
let missing = 0;

for (const path of guides()) {
    const key = relative(join(ROOT, "guidelines"), path).replace(/\.md$/, "");
    const contract = map[key];
    if (!contract) {
        missing++;
        console.error(`no accessibility contract for guidelines/${key}.md — add it to guidelines/a11y-map.json`);
        continue;
    }
    const text = readFileSync(path, "utf8");
    const next = text.includes(START) ? text.replace(new RegExp(`${START}[\\s\\S]*?${END}`), () => section(contract)) : `${text.trimEnd()}\n\n${section(contract)}\n`;
    if (next === text) continue;
    stale++;
    if (check) console.error(`stale accessibility section: guidelines/${key}.md`);
    else writeFileSync(path, next);
}

if (check && (stale || missing)) process.exit(1);
if (missing) process.exit(1);
console.log(check ? "accessibility sections: up to date" : `accessibility sections: ${stale} rewritten`);
