/**
 * Rewrites the prop table in every guide from the source types.
 *
 * A hand-written prop table is a copy of the truth, and copies rot. Only the text
 * between the markers is touched, so the prose around it is safe to edit by hand.
 * Run with `--check` in CI: it writes nothing and fails if a table is out of date.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { components, ROOT } from "./components.mjs";

const START = "<!-- props:start -->";
const END = "<!-- props:end -->";

const table = (component) => {
    const rows = (component.type?.props || []).map((p) => {
        const type = component.unions[p.type] ? `${p.type} — ${component.unions[p.type]}` : p.type;
        return `| \`${p.name}\` | \`${type}\` | ${p.required ? "yes" : "no"} | ${p.doc || "—"} |`;
    });
    const inherited = component.type?.extends ? `\nInherits every prop of \`${component.type.extends}\`.\n` : "";
    return [
        START,
        `<!-- generated by scripts/props.mjs from ${component.file} — do not edit -->`,
        "",
        "| Prop | Type | Required | What it does |",
        "| :-- | :-- | :-- | :-- |",
        ...(rows.length ? rows : ["| — | — | — | This component takes no props of its own. |"]),
        inherited,
        END,
    ].join("\n");
};

let stale = 0;
for (const component of components()) {
    const path = join(ROOT, "guidelines", `${component.slug}.md`);
    const text = readFileSync(path, "utf8");
    const next = text.includes(START)
        ? text.replace(new RegExp(`${START}[\\s\\S]*?${END}`), () => table(component))
        : `${text.trimEnd()}\n\n## Props\n\n${table(component)}\n`;
    if (next === text) continue;
    stale++;
    if (process.argv.includes("--check")) console.error(`stale prop table: guidelines/${component.slug}.md`);
    else writeFileSync(path, next);
}

if (process.argv.includes("--check") && stale) {
    console.error(`\n${stale} prop table(s) out of date. Run \`npm run docs:props\` and commit the result.`);
    process.exit(1);
}
console.log(process.argv.includes("--check") ? "prop tables: up to date" : `prop tables: ${stale} rewritten`);
